SELECT SEQ,USER_ID,USER_PW,USER_NAME,EMAIL,NVL(USER_RECORD,0) AS user_record ,REGDATE,GRADE,ENABLED FROM ROOMUSER WHERE USER_ID='15queue' AND USER_PW='10041004' AND ENABLED='Y'



INSERT INTO HK.ROOMUSER
(SEQ, USER_ID, USER_PW, USER_NAME, EMAIL, REGDATE, GRADE, ENABLED, USER_RECORD)
VALUES(ROOMUSER_SEQ.NEXTVAL, '10', '10041004', '정요섭', '15queue@hanmail.net', SYSDATE, 'BRONZE', 'Y', NULL);

INSERT INTO HK.ROOMUSER
(SEQ, USER_ID, USER_PW, USER_NAME, EMAIL, REGDATE, GRADE, ENABLED, USER_RECORD)
VALUES(ROOMUSER_SEQ.NEXTVAL, 'admin', 'admin', '정요섭', '15queue@hanmail.net', SYSDATE, 'admin', 'Y', NULL);


SELECT SEQ ,USER_ID ,USER_PW , USER_NAME , EMAIL , USER_RECORD , REGDATE , GRADE , ENABLED FROM ROOMUSER WHERE USER_ID='15queue' AND USER_PW='10041004' AND ENABLED='Y'


INSERT INTO HK."RESULT"(RESULTROOM)VALUES('1');
COMMIT;
TRUNCATE TABLE roomuser;

UPDATE HK.ROOMUSER
SET GRADE='ADMIN'
WHERE USER_ID='15queue';
